[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
